[package]
  name = "markdown-parser"
  version = "0.1.0"
  edition = "2021"
  authors = ["princemuel <vansomecsam@gmail.com>"]


[lib]
  crate-type = ["cdylib"]

[dependencies]
  wasm-bindgen = "0.2"
